name: Build and deploy mkdocs

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install python modules
        run: |
          python -m pip install -U pip
          pip install mkdocs-material
          pip install mkdocs-glightbox

      - name: Set site path to env
        run: |
          echo "site_path=$(realpath ../site)" >> $GITHUB_ENV

      - name: mkdocs local build
        run: |
          cd mkdocs
          mkdocs build --clean --no-directory-urls --site-dir ../../site

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LocalSite
          path: ${{ env.site_path }}

      - name: mkdocs io build
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          cd mkdocs
          mkdocs build --clean --use-directory-urls --site-dir ../../site

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.site_path }}

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
