# This is a basic workflow to help you get started with Actions

name: Deploy mkdocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions for the workflow
permissions:
  # The permissions required by the GitHub token to check out code
  contents: read
  # The permissions required by the GitHub token to deploy to GitHub Pages
  pages: write
  # The permissions required by the GitHub token to upload artifacts
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Setup python
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Install python modules
      - name: Install python modules
        run: |
          python -m pip install -U pip
          pip install mkdocs-material

      # Set site path to env
      - name: Set site path to env
        run: |
          echo "site_path=$(realpath ../site)" >> $GITHUB_ENV

      # Build and deploy local build
      - name: mkdocs local build
        run: |
          cd mkdocs
          mkdocs build --clean --no-directory-urls --site-dir ../../site
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LocalSite
          path: ${{ env.site_path }}

      # Build and deploy to GitHub Pages
      - name: mkdocs io build
        run: |
          cd mkdocs
          mkdocs build --clean --use-directory-urls --site-dir ../../site
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.site_path }}
      - name : Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
