site_name: About shirokuma1101
site_url: https://shirokuma1101.github.io/shirokuma1101/
site_description: About shirokuma1101.
site_author: Takuma Shirooka

repo_name: shirokuma1101
repo_url: https://github.com/shirokuma1101/shirokuma1101
docs_dir: '..'
edit_uri: edit/main/

copyright: Copyright © 2024 Takuma Shirooka (shirokuma1101)

theme:
  name: material
  language: ja
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - content.action.view
    - content.code.copy
    - navigation.expand
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Noto Sans JP'
    code: 'Inconsolata'
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: README.md
  - Portfolio:
    - Summary: portfolio/portfolio.md
    - Works:
      - Noctem: portfolio/works/noctem.md
      - game-libraries: portfolio/works/gamelibraries.md
      - All Your Weapons: portfolio/works/allyourweapons.md
      - Prank Heart: portfolio/works/prankheart.md
      - Other works: portfolio/works/otherworks.md
    - Skills: portfolio/skills/skills.md
    - Hobby:
      - Hobby: portfolio/hobby/hobby.md
      - Gallery: portfolio/hobby/gallery.md
      - Network Chart: portfolio/hobby/networkchart.md
  - Note:
    - StyleGuide: note/styleguide.md
    - VscodeSetting: note/vscodesetting.md

extra_css:
  - css/extra.css

extra:
  search:
    language: ja
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shirokuma1101
      name: shirokuma1101 on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kd_shirokuma
      name: kd_shirokuma on Twitter
  consent:
    title: Cookie Policy
    description: Obtain cookies to obtain your information.
    actions:
      - accept
      - reject
      - manage
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      #noclasses: true
      #pygments_style: monokai
      #use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox:
      manual: true

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
