site_name: About shirokuma1101
site_url: https://shirokuma1101.github.io/shirokuma1101/
site_description: About shirokuma1101.
site_author: Takuma Shirooka

repo_name: shirokuma1101
repo_url: https://github.com/shirokuma1101/shirokuma1101
docs_dir: '..'

copyright: Copyright © 2024 Takuma Shirooka (shirokuma1101)

theme:
  name: material
  language: ja
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Noto Sans JP'
    code: 'Inconsolata'
  palette:
    - scheme: default
      primary: blue
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: README.md
  - Portfolio:
    - Summary: portfolio/portfolio.md
    - Works:
      - Game Libraries: portfolio/works/gamelibraries.md
      - All Your Weapons: portfolio/works/allyourweapons.md
      - Noctem: portfolio/works/noctem.md
      - Prank Heart: portfolio/works/prankheart.md
    - Hobby: portfolio/hobby/hobby.md
  - Note:
    - StyleGuide: note/styleguide.md

extra_css:
  - css/extra.css

extra:
  search:
    language: ja
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shirokuma1101
      name: shirokuma1101 on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kd_shirokuma
      name: kd_shirokuma on Twitter
  consent:
    title: Cookie Policy
    description: Obtain cookies to obtain your information.
    actions:
      - accept
      - reject
      - manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
